# Builds SnapCut.exe (快截) using the C# compiler that ships with Windows (.NET Framework 4.x).
# No SDK, no NuGet. On Win10/11 it auto-detects the built-in WinRT metadata and enables
# offline OCR (/define:OCR). If that isn't available, it falls back to a build without OCR.
param([string]$Message = "", [switch]$Bump)

$ErrorActionPreference = "Stop"

$csc = "$env:WINDIR\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) { $csc = "$env:WINDIR\Microsoft.NET\Framework\v4.0.30319\csc.exe" }
if (-not (Test-Path $csc)) { throw "csc.exe not found - .NET Framework 4.x is required (preinstalled on Win8+)." }

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$out  = Join-Path $root "build"
New-Item -ItemType Directory -Force -Path $out | Out-Null

# ---- version: Major.Minor.Patch（三段）。版本号以 version.txt 为准，
# 只有显式传 -Bump 才自增末位 —— 版本变更需人工确认，日常构建不再偷偷改版本。 ----
$versionFile = Join-Path $root "version.txt"
$baseVer = "1.0.0"
if (Test-Path $versionFile) {
    $raw = (Get-Content $versionFile -Raw).Trim()
    if ($raw) { $baseVer = $raw }
}
# 兼容旧四段版本号（如 1.1.0.18）：只取前三段
$vp = $baseVer.Split('.')
if ($vp.Count -gt 3) { $vp = $vp[0..2] }
while ($vp.Count -lt 3) { $vp += "0" }
if ($Bump) { $vp[2] = ([int]$vp[2] + 1).ToString() }
$version = ($vp[0..2] -join '.')
# 注意：version.txt 在编译成功后才写入，失败的构建不消耗版本号

# generated assembly version info - compiled together with src\*.cs
$asmInfo = Join-Path $root "src\AssemblyInfo.cs"
@"
// <auto-generated> Regenerated by build.ps1 on every build. Do not edit by hand. </auto-generated>
using System.Reflection;
[assembly: AssemblyTitle("SnapCut")]
[assembly: AssemblyProduct("SnapCut")]
[assembly: AssemblyCompany("SnapCut")]
[assembly: AssemblyDescription("快截 - WeChat-style screenshot, scrolling capture, OCR and screen recorder")]
[assembly: AssemblyVersion("$version")]
[assembly: AssemblyFileVersion("$version")]
"@ | Set-Content -Path $asmInfo -Encoding UTF8

$exe      = Join-Path $out "SnapCut.exe"
$manifest = Join-Path $root "src\app.manifest"
$common   = @(
    "/nologo", "/target:winexe", "/optimize+", "/unsafe", "/platform:anycpu",
    "/codepage:65001",
    "/win32manifest:$manifest",
    "/out:$exe",
    "/r:System.dll", "/r:System.Drawing.dll", "/r:System.Windows.Forms.dll"
)

# ---- locate the built-in WinRT metadata + interop assemblies for offline OCR ----
# Win10/11 ships per-namespace .winmd files in System32\WinMetadata, and the .NET
# Framework provides System.Runtime.WindowsRuntime.dll for the async projections.
$ocrRefs = @()
$wm = "$env:WINDIR\System32\WinMetadata"
$fwDir = Split-Path -Parent $csc
$rtWinRT = Join-Path $fwDir "System.Runtime.WindowsRuntime.dll"
$rt = Join-Path $fwDir "System.Runtime.dll"
$needWinmd = @("Windows.Foundation", "Windows.Graphics", "Windows.Media", "Windows.Storage", "Windows.Globalization")
$haveAll = (Test-Path $rtWinRT) -and (Test-Path $rt)
foreach ($n in $needWinmd) { if (-not (Test-Path (Join-Path $wm "$n.winmd"))) { $haveAll = $false } }
if ($haveAll) {
    $ocrRefs += "/r:$rt"
    $ocrRefs += "/r:$rtWinRT"
    foreach ($n in $needWinmd) { $ocrRefs += "/r:$(Join-Path $wm ""$n.winmd"")" }
}

$src = Get-ChildItem "$root\src\*.cs" | ForEach-Object { $_.FullName }

# ---- 若 plugins\ffmpeg\ffmpeg.exe 存在，则嵌入 exe 实现单文件分发 ----
# 运行时由 Ffmpeg.ExtractEmbedded() 释放到 %LocalAppData%\SnapCut\ 后调用，
# 最终用户无需安装 ffmpeg，也无需 plugins 目录。
$ffRes = Join-Path $root "plugins\ffmpeg\ffmpeg.exe"
$resArgs = @()
if (Test-Path $ffRes) { $resArgs = @("/resource:$ffRes,SimpleShot.ffmpeg.exe") }

# ---- 应用图标：src\app.ico 由程序自身绘制导出（SnapCut.exe --write-icon），
# 供 exe / 安装包 / 快捷方式共用；缺失时用上一版已构建的 exe 现场生成。 ----
$ico = Join-Path $root "src\app.ico"
if (-not (Test-Path $ico) -and (Test-Path $exe)) {
    & $exe "--write-icon" $ico 2>&1 | Out-Null
}
$iconArgs = @()
if (Test-Path $ico) { $iconArgs = @("/win32icon:$ico") }

$ocrEnabled = $false
if ($ocrRefs.Count -gt 0) {
    Write-Host "Attempting build WITH built-in OCR..." -ForegroundColor Cyan
    & $csc @common "/define:OCR" @ocrRefs @resArgs @iconArgs @src 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) { $ocrEnabled = $true }
    else { Write-Host "OCR build failed - falling back to no-OCR build." -ForegroundColor Yellow }
}

if (-not $ocrEnabled) {
    & $csc @common @resArgs @iconArgs @src
}

if ($LASTEXITCODE -eq 0) {
    $size = (Get-Item $exe).Length
    $ocrMsg = if ($ocrEnabled) { "OCR: enabled" } else { "OCR: disabled" }

    # 注：ffmpeg 已作为资源嵌入 exe，不再复制到输出目录（避免分发体积翻倍）

    Set-Content -Path $versionFile -Value $version -Encoding ASCII

    # ---- changelog: prepend a dated entry for this successful build ----
    # 注意：必须显式指定 UTF8 读写，否则 PS5.1 会按系统 ANSI(GBK) 误读无 BOM 文件导致中文乱码
    $changelog = Join-Path $root "CHANGELOG.md"
    $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $note  = if ($Message) { $Message } else { "常规构建。" }
    $ocrMsg  = if ($ocrEnabled) { "OCR 已启用" } else { "OCR 未启用" }
    # 只保留有价值的变更说明；"构建：OCR/体积"这类编译信息不写入更新日志
    $entry = "## v$version - $stamp`r`n- $note`r`n`r`n"
    $header = "# 快截 (SnapCut) 更新日志`r`n`r`n"
    if (Test-Path $changelog) {
        $old = Get-Content $changelog -Raw -Encoding UTF8
        # 同一版本重复构建：先移除旧条目再写入，保证每个版本只有一条记录
        $same = "(?ms)^## v" + [regex]::Escape($version) + " - .*?(?=^## v|\z)"
        $old = [regex]::Replace($old, $same, "")
        if ($old -match "(?s)^(#[^\r\n]*\r?\n\r?\n)(.*)$") {
            $content = $Matches[1] + $entry + $Matches[2]
        } else {
            $content = $header + $entry + $old
        }
    } else {
        $content = $header + $entry
    }
    Set-Content -Path $changelog -Value $content -Encoding UTF8
    # ship the changelog next to the exe so the app can display it
    Copy-Item $changelog (Join-Path $out "CHANGELOG.md") -Force

    # ---- 整理输出目录：删除运行时不需要的文件（单 exe 即可运行）----
    # ffmpeg 已嵌入 exe；内置 OCR 不依赖插件；抠图入口默认隐藏，
    # 即使启用后缺插件也会优雅提示（模型仍在源码 plugins\ 下，需要时可拷回）。
    foreach ($junk in @("AviTest.exe", "SimpleShot.exe", "plugins")) {
        $jp = Join-Path $out $junk
        if (Test-Path $jp) { Remove-Item $jp -Recurse -Force -ErrorAction SilentlyContinue }
    }

    # ---- 便携分发包：单 exe + 更新日志 打成 zip ----
    $zip = Join-Path $out ("SnapCut-v" + $version + "-portable.zip")
    if (Test-Path $zip) { Remove-Item $zip -Force -ErrorAction SilentlyContinue }
    Compress-Archive -Path $exe, (Join-Path $out "CHANGELOG.md") -DestinationPath $zip -CompressionLevel Optimal

    Write-Host ("Build OK -> build\SnapCut.exe  v{0}  ({1:N0} bytes / {2:N1} KB)  [{3}]" -f $version, $size, ($size/1KB), $ocrMsg) -ForegroundColor Green
    Write-Host ("Portable ZIP -> {0}  ({1:N1} MB)" -f (Split-Path $zip -Leaf), ((Get-Item $zip).Length/1MB)) -ForegroundColor Green

    # ---- 清理历史版本的打包产物：只保留当前版本，避免 build 目录越堆越多 ----
    Get-ChildItem -LiteralPath $out -File -ErrorAction SilentlyContinue | Where-Object {
        ($_.Name -like "SnapCut-v*-portable.zip" -and $_.Name -ne ("SnapCut-v" + $version + "-portable.zip")) -or
        ($_.Name -like "SnapCut-Setup-v*.exe" -and $_.Name -ne ("SnapCut-Setup-v" + $version + ".exe"))
    } | ForEach-Object { Remove-Item $_.FullName -Force -ErrorAction SilentlyContinue }

    # ---- 安装包（Inno Setup）：本机装有 ISCC 时自动生成 ----
    $iscc = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) "Programs\Inno Setup 6\ISCC.exe"
    if (-not (Test-Path $iscc)) { $iscc = Join-Path ${env:ProgramFiles(x86)} "Inno Setup 6\ISCC.exe" }
    if (-not (Test-Path $iscc)) { $iscc = Join-Path ${env:ProgramFiles} "Inno Setup 6\ISCC.exe" }
    if (Test-Path $iscc) {
        Write-Host "Building installer (Inno Setup)..." -ForegroundColor Cyan
        # 先删旧安装包：ISCC 直接写目标文件，若构建中途被打断会留下残缺文件，
        # 运行时报 "The setup files are corrupted"。删掉后中断只会表现为"文件不存在"。
        $setup = Join-Path $out ("SnapCut-Setup-v" + $version + ".exe")
        if (Test-Path $setup) { Remove-Item $setup -Force -ErrorAction SilentlyContinue }
        & $iscc "/O$out" "/DMyAppVersion=$version" (Join-Path $root "installer.iss") | Out-Null
        $setup = Join-Path $out ("SnapCut-Setup-v" + $version + ".exe")
        if ($LASTEXITCODE -eq 0 -and (Test-Path $setup)) {
            Write-Host ("Installer    -> {0}  ({1:N1} MB)" -f (Split-Path $setup -Leaf), ((Get-Item $setup).Length/1MB)) -ForegroundColor Green
        } else {
            Write-Host "Inno Setup 编译失败（exe 与便携包不受影响）。" -ForegroundColor Yellow
        }
    } else {
        Write-Host "未找到 Inno Setup (ISCC.exe)，跳过安装包生成。" -ForegroundColor DarkGray
    }
} else {
    throw "Build failed."
}
