// <auto-generated> Regenerated by build.ps1 on every build. Do not edit by hand. </auto-generated>
using System.Reflection;
[assembly: AssemblyTitle("SnapCut")]
[assembly: AssemblyProduct("SnapCut")]
[assembly: AssemblyCompany("SnapCut")]
[assembly: AssemblyDescription("快截 - WeChat-style screenshot, scrolling capture, OCR and screen recorder")]
[assembly: AssemblyVersion("1.2.1")]
[assembly: AssemblyFileVersion("1.2.1")]
